[security]
allowed-users = ["ivy"]

[jail]
backend = "systemd-run"

[github]
project-id = "29"
project-node-id = "PVT_kwHOADgWUM4BOsG3"
status-field-id = "PVTSSF_lAHOADgWUM4BOsG3zg9UQiM"
in-progress-option-id = "6e4a1660"
in-review-option-id = "1b866fe9"
